// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkdxjinnqchgtgbtegfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrZHhqaW5ucWNoZ3RnYnRlZ2ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODgwODQsImV4cCI6MjA2OTk2NDA4NH0.NocQCAbVa-SPsBKwBb2MAjMbMd0B_XzT5qY1zaHCe6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});